name: ignis
description: Flutter game engine.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter
  ivector_math: ^0.0.4
  pool: ^1.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  benchmark_harness: ^2.3.1
  flame: ^1.38.0
  flutter_lints: ^6.0.0
  leak_tracker: ^11.0.2
  vm_service: ^15.2.0
scripts:
  analyze: dart analyze
  coverage:
    $script: flutter test --coverage
    $after: genhtml coverage/lcov.info -o coverage/html
  goldens: flutter test --update-goldens
  open-coverage: open coverage/html/index.html
  test: flutter test
flutter:
  assets:
    - test/assets/
  shaders:
    - test/shaders/sample.frag
