include: ../analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/**/*.imports.dart
    - lib/generated/**
    - lib/main.client.options.dart
    - lib/main.server.options.dart
    - web/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**
